export enum AuthActionTypes {
    SET_PUBLIC_TOKEN = 'SET_PUBLIC_TOKEN',
    SET_AUTH_TOKEN = 'SET_AUTH_TOKEN',
    SET_USER = 'SET_USER',
    REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN',
    EXPIRED_PUBLIC_TOKEN = 'EXPIRED_PUBLIC_TOKEN',
    SHOW_ONBOARDING = 'SHOW_ONBOARDING',
    HIDE_ONBOARDING = 'HIDE_ONBOARDING',
}
